Features
VICTOR-CHUKWU/Hello-Microverse pull request #1
Opened 2021-08-10 17:20 UTC by VICTOR-CHUKWU

I worked on testing my git-flow

2021-08-10 17:52 UTC, safafa requested changes
## STATUS: CHANGES REQUESTED ♻️ 

Hi @VICTOR-CHUKWU , You did a great job so far 👏🏼 👏🏼 

- The GithubFlow is correctly used.

However, here are some points that you need to work on to get your project approved.

## Required changes :

Check the inline comments.

## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-10 17:52 UTC, safafa commented on readme.md
> +a hello microverse project to test my git and esLint knowledge
- [ ] For your project to look professional. The Readme file should be descriptive. Kindly modify it you can use [Microverse Template](https://github.com/microverseinc/readme-template)

2021-08-10 17:52 UTC, safafa commented on style.css
> +    color: white;  }
- [ ] The Stylelint linter is not passing. Kindly fix the problem before asking for another review.  
- [ ] I think it would be better to use descriptive commits messages. You can check this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) on how to create professional messages.
- [ ] kindly modify the pull request link it should be related to the current changes  . 
- [ ] Please submit the pull request title instead of the project link when you request for a review .

2021-08-11 08:19 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @VICTOR-CHUKWU, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<hr>

You did an amazing job, I know you have the skills enough to finish these changes required in time 😉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 08:19 UTC, DanteAlonsoHT commented on readme.md
> +
Remove Live Demo section due to it's empty unless you want to use  Github Pages to deploy this project.

- [ ] Remove Live Demo section.

2021-08-11 08:19 UTC, DanteAlonsoHT commented on readme.md
> +This project is [MIT](./MIT.md) licensed.
This link is not working, you should fix it by adding the MIT License file in your repository or adding the right link to make a reference with MIT License.

- [ ] Fix MIT License link.

2021-08-11 08:19 UTC, DanteAlonsoHT commented on readme.md
> +- GitHub: [@githubhandle](https://github.com/VICTOR-CHUKWU)
Inside the "[ ]" you can put "Victor-Github" instead of "@githubhandle" to make it more professional, also I strongly recommend you to add your social media for Twitter and LinkedIn.

- [ ]  Change the name inside " [ ] " for the Github link in the Authors section.
- [ ]  [OPTIONAL] Add your Twitter and LinkedIn.

2021-08-11 09:53 UTC, AshakaE approved these changes
### Hi @VICTOR-CHUKWU  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 12:13 UTC, merged